name: build and test
on:
  push:
    branches-ignore:
      - main
env:
  BEFORE_SHA: ${{ github.event.before }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  test:
    name: lint and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.4.0
        uses: actions/setup-node@v1
        with:
          node-version: 16.4.0
      - name: config private registry
        run: npm config set '@surge-global-engineering:registry' "https://npm.pkg.github.com"
      - run: npm config set '//npm.pkg.github.com/:_authToken' "${GITHUB_TOKEN}"
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: npm install
        if: steps.cache-primes.outputs.cache-hit != 'true'
        run: npm install

      - name: running lint on test-app
        run: npm run lint app

      - name: running lint on react-pdf-components
        run: npm run lint react-pdf-components

      - name: building app and lib
        run: npm run build
