name: deploy
on:
  pull_request:
    branches:
      - main
    types: [closed]
env:
  BEFORE_SHA: ${{ github.event.before }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
  PR_NUMBER: ${{ github.event.number }}
jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Use Node.js 16.4.0
        uses: actions/setup-node@v1
        with:
          node-version: 16.4.0

      - name: config private registry
        run: npm config set '@surge-global-engineering:registry' "https://npm.pkg.github.com"
      - run: npm config set '//npm.pkg.github.com/:_authToken' "${GITHUB_TOKEN}"
      # caching deps

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: install firebase
        run: npm i firebase-tools -g

      - name: install dependencies
        if: steps.cache-primes.outputs.cache-hit != 'true'
        run: npm install

      - name: building app and lib
        run: npm run build app
      - name: deploy for preview
        run: firebase deploy --only hosting --token $FIREBASE_TOKEN

  publish-pkg:
    # deploy package to github packages
    runs-on: ubuntu-latest
    steps:
      # Setup
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Use Node.js 16.4.0
        uses: actions/setup-node@v1
        with:
          node-version: 16.4.0

      - name: config private registry
        run: |
          npm config set '@surge-global-engineering:registry' "https://npm.pkg.github.com"
          npm config set '//npm.pkg.github.com/:_authToken' "${GITHUB_TOKEN}"

      - name: npm install
        run: npm install

      - name: bump version
        run: ./.github/scripts/bump-version.sh

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
        with:
          path: libs/react-pdf-components

      - name: build
        run: npm run build react-pdf-components

      - name: publish to github packages
        working-directory: ./dist/libs/react-pdf-components
        run: npm publish --no-push --yes

      - name: Commit changes
        # if: github.event.pull_request.merged == true && contains(github.event.commits[0].message, '[skip-ci]') == false
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Release Commit [no ci]"

      - name: git tag
        run: git tag -a ${{ steps.package-version.outputs.current-version}} -m "release tag ${{ steps.package-version.outputs.current-version}}"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN  }}
          branch: ${{ github.ref }}
          tags: true
          force: true
